### ISSUE TITLE
Menu replacment idea

### ISSUE THREAD

**Issue by rgocal** [KeikaiLauncher/KeikaiLauncher#13]
https://github.com/rgocal/Material_PopUp_Menu

I think this would look a heck of alot better for a menu system per app.

**Comment by avuton** [comment]
I, personally, wouldn't add features that have a stock implementation.

**Comment by avuton** [comment]
Thanks for the issue, but, I doubt implementation will occur in this tree and it's not wise to leave this issue open indefinitely. Reopen if there is more to do here.
