### ISSUE TITLE
Can't detect apps in a work profile

### ISSUE THREAD

**Issue by ArenaL5** [KeikaiLauncher/KeikaiLauncher#15]
(Edited three times because I can't keep my markup straight.)

Issue
=====

Applications in a work profile can be seen in the original app launcher, but not in Keikai Launcher. Notice how «Contactos» and «Descargas» are duplicated in the built-in launcher; the apps marked with the briefcase icon are inside a work profile, and can't be accessed from Keikai Launcher.

![Stock launcher](https://user-images.githubusercontent.com/37388405/51388385-2c24f100-1b21-11e9-8793-dd1f33561d39.png)
![Keikai Launcher](https://user-images.githubusercontent.com/37388405/51388390-2deeb480-1b21-11e9-98eb-7b5fb58f768e.png)

Details about this work profile
=====

I'm using [Island](https://forum.xda-developers.com/android/apps-games/closed-beta-test-incoming-companion-app-t3366295), an application that abuses the [Android work profile](https://developers.google.com/android/work/requirements/work-profile) to isolate applications.

Island creates a managed profile with its own storage space, contacts and calendar. Normal applications can only access the profile in which are installed, allowing me to clone apps with different data, or isolate apps from certain data.

I still can access the applications in the work profile through Island itself, but not through the launcher. Attempting to use an older launcher just throws an Android error message, paraphrased: “This application does not support work profiles.”

Warning
=====

Island has internet permissions and has attempted to connect to internet in the past. It's probably for Google statistics, but you may want to use a precaution to avoid this. Or use an alternative like [Shelter](https://f-droid.org/en/packages/net.typeblog.shelter/), if it works for you. (Shelter is not compatible with Marshmallow.)

Technical data (probably not relevant)
=====

Smartphone: Wiko Lenny 3
OS: LENNY3 Marshmallow 6.0 (59) [stock Android, customized by Wiko]
Last security patch: 5th of November, 2017
Rooted with Magisk Manager

Thanks
======

Keikai Launcher works perfectly otherwise, much better than the __terrible__ original launcher. Also, it doesn't prompt you to download bloatware.

**Comment by avuton** [comment]
Unfortunately, this didn't even hit my radar. I'm sure I could easily add support for profiles, but UI probably wouldn't be as easy. I'm going to look into it if I get some extra time in $life.

**Comment by avuton** [comment]
Better late than never. I'll probably be committing this soon. It'd be great if I could get a hand with testing, because my use case for work profile is really minimal.
