### ISSUE TITLE
Ability to hide apps

### ISSUE THREAD

**Issue by esmoak** [KeikaiLauncher/KeikaiLauncher#8]
First, congratulations on a successful fork.

I’d love to see the ability to hide apps. Perhaps how it is implemented in: 
FAST App Search Tool (Find apps just by typing) - https://f-droid.org/app/org.ligi.fast

https://github.com/ligi/FAST

**Comment by avuton** [comment]
(My 2c) I'd like to see this, as well, I couldn't think of a way to make it happen while preventing [code] complexity. Hope someone can come along and implement this in a clean way. The UI I always imagined is once an app is hidden, it will pop up at the end of the ListView when searched which is how it would be unhidden.

**Comment by esmoak** [comment]
@avuton Thanks for your input. That does sound like a nice potential implementation. Many thanks to those of you who code. I wish I could contribute in that way.

**Comment by ghost** [comment]
Is there any progress on adding this feature?
